# Generated by Django 2.2.6 on 2019-10-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20191012_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='urlTo',
            new_name='link',
        ),
    ]
